log:
    level: "INFO"

dataset:
  # [数据根目录]
  data_root: "/mnt/data/home/tycloud/workspace/algorithms_raw/data/HSPC/"
  # 原始数据目录
  raw_dir: "/mnt/data/home/tycloud/workspace/algorithms_raw/data/HSPC/raw/"
  # 处理后数据目录
  processed_dir: "/mnt/data/home/tycloud/workspace/algorithms_raw/data/HSPC/processed/"

  force_reload: False

  # [图的数量]
  # 定义原始数据文件包含几张图
  # 每一张图均对应以下三个文件，其中i表示从0开始编号的第几张图
  # 1、graph_i_nodes.csv：存储第i张图的节点特征
  #   文件示例:
  #   id,feature1,feature2,...
  #   0,1.0,2.0,...
  #   1,2.1,3.4,...
  #   2,3.5,4.2,...
  #   3,1.3,0.8,...
  # 2、graph_i_edges.csv：存储第i张图的边特征，第一列和第二列名必须为srt和dst
  #   文件示例:
  #     src,dst,feature1,feature2,...
  #     0,1,0.1,0.2,...
  #     1,2,0.3,0.4,...
  #     2,3,0.5,0.6,...
  #     3,0,0.7,0.8,...
  # 3、[可选]graph_i_node_names.csv： 存储第i张图中每一个节点的名称
  #   文件示例(列名也需和该示例保持一致，type列可省略):
  #     name,type
  #     node0,type0
  #     node1,type1
  #     node2,type2
  #     node3,type3

  num_graphs: 1

  # [是否使用节点名称]
  # 不使用节点名称时node文件的第一列和edge文件的前两列需为节点id
  # 即node文件中除表头外，第一列从0开始按行编号且编号必须连续
  # edge文件前两列表示边的起点与终点的节点id，均对应node文件第一列中的id值
  # 若使用节点名称，则必须提供graph_i_node_names.csv文件
  # 该文件第一列为节点名称，若为异构图，还需要有第三列存储节点类型
  # 每个节点的id为从上到下排序从0开始的行号，如果异构图，则不同类型的节点分别编号形成id
  # 这时graph_i_nodes.csv和graph_i_edges.csv文件的节点id全部需要替换为对应的节点名称
  use_node_name: true

  # [是否读取图标签]
  # 如果为true需要增加图标签文件
  # 文件名固定为graph_labels.csv
  # 文件示例
  # graph_id,label
  # 0,0
  # 1,1
  # 2,0
  use_graph_labels: false

  # [节点label列名]
  # 指定graph_i_nodes.csv中某一列为该节点的label
  # 为空为表示不设置节点label
  node_label_column:
  # [边时间戳列名]
  # 指定graph_i_edges.csv中某一列为为该条边的时间戳
  # 为空为表示不设置边时间戳
  edge_timestamp_column:
  # [边类型列名]
  # 指定graph_i_edges.csv中某一列为为该条边的label
  # 为空为表示不设置边类型
  edge_type_column:
  # [边label列名]
  # 指定graph_i_edges.csv中某一列为为该条边的label
  # 为空为表示不设置边边label
  edge_label_column:

  # [是否为真实边列名]
  # 先验网络中只有一部分为真实的网络，它的信息存在特定的一列，1是真实的；0是先验的。
  # 如果为空，就认为所有先验边都是真实的
  edge_id_T: edge_id_T

  # 是否将原始数据中的多张图合并
  merge_graphs: true

  # 随机数种子，随机切分为测试集和训练集
  seed: 42

  # 测试集比例
  rate: 0.2

model:
  hidden_dim: 16
  num_layer: 2
  embedding_dim: 8

  # 负样本数量是正样本的多少倍
  Negative_rate: 1

training:
  batch_size: 1
  shuffle: False
  epochs: 1000
  learning_rate: 0.001
  model_save_path: "/mnt/data/home/tycloud/workspace/algorithms_raw/data/HSPC/best_model.pth"
